In [1]:
import numpy as np

In [6]:
s = np.array([5])
print("=========")
print(s.ndim)
print(s.shape)
v = np.array([1, 2, 3])
print("=========")
print(v.ndim)
print(v.shape)
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print("=========")
print(m.ndim)
print(m.shape)


1
(1,)
1
(3,)
2
(3, 3)


In [8]:
vec_1 = np.array([1, 2, 3, 4, 5, 6])
mat_1 = vec_1.reshape(3, 2)
print(vec_1)
print(mat_1)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [10]:
vec_2 = np.array([1, 2, 3, 4, 5, 6])
mat_2 = vec_2.reshape(vec_2.shape[0], 1)
print(vec_2)
print(mat_2)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
vec_2[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
class c:
    x=3
o1 = c()

In [25]:
mat = np.array(
    [
        [False, True, "Ali"],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(mat)
print(mat.dtype)

[['False' 'True' 'Ali']
 ['4' '5' '6']
 ['7' '8' '9']]
<U21


In [ ]:
# priority 
object , str , float , int , bool

In [1]:
import numpy as np

In [2]:
mat_1 = np.ones((3, 4))
mat_2 = np.zeros((5, 3))

In [5]:
np.savez('test.npz', ones_mat=mat_1, zeros_mat=mat_2)

In [7]:
with np.load('test.npz') as data:
    ones_mat = data['ones_mat']
    zeros_mat = data['zeros_mat']
print(ones_mat)
print(zeros_mat)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
m1= np.array([[1,2,3],    # بتضم الماتركس مع بعض
              [4,5,6]]
            )
m2 = np.array([[7,8,9],
              [10,11,12]]
            )
vertical_mat = np.hstack((m1, m2))
print(vertical_mat)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [13]:
# to compare
s = 2
v = np.array([1, 2, 3])

v == s

array([False,  True, False])

In [15]:
v = np.array([1, 2, 3])
np.any(v>1)

np.True_

In [18]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.isclose(v1, v2,atol=3)


array([ True,  True,  True])

In [19]:
v = np.array([2,4,3,4,10])
condition = v > 5
cond_access = v[condition]
print(cond_access)

[10]
