In [1]:
import numpy as np

In [6]:
s = np.array([5])
print("=========")
print(s.ndim)
print(s.shape)
v = np.array([1, 2, 3])
print("=========")
print(v.ndim)
print(v.shape)
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print("=========")
print(m.ndim)
print(m.shape)


1
(1,)
1
(3,)
2
(3, 3)


In [8]:
vec_1 = np.array([1, 2, 3, 4, 5, 6])
mat_1 = vec_1.reshape(3, 2)
print(vec_1)
print(mat_1)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


In [10]:
vec_2 = np.array([1, 2, 3, 4, 5, 6])
mat_2 = vec_2.reshape(vec_2.shape[0], 1)
print(vec_2)
print(mat_2)

[1 2 3 4 5 6]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
vec_2[:, None]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [22]:
class c:
    x=3
o1 = c()

In [25]:
mat = np.array(
    [
        [False, True, "Ali"],
        [4, 5, 6],
        [7, 8, 9]
    ]
)
print(mat)
print(mat.dtype)

[['False' 'True' 'Ali']
 ['4' '5' '6']
 ['7' '8' '9']]
<U21


In [ ]:
# priority 
object , str , float , int , bool